// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductCRUD.Data;

#nullable disable

namespace ProductCRUD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524160814_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ProductCRUD.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "อาหาร เครื่องดื่ม และของกินเล่น",
                            Name = "Food & Drinks"
                        },
                        new
                        {
                            Id = 2,
                            Description = "เครื่องใช้ไฟฟ้าภายในบ้านและห้องครัว",
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 3,
                            Description = "อุปกรณ์อิเล็กทรอนิกส์และสินค้าไอที",
                            Name = "Electronics & IT"
                        },
                        new
                        {
                            Id = 4,
                            Description = "เสื้อผ้า แฟชั่น และเครื่องแต่งกาย",
                            Name = "Clothing & Fashion"
                        },
                        new
                        {
                            Id = 5,
                            Description = "ผลิตภัณฑ์สุขภาพและความงาม",
                            Name = "Health & Beauty"
                        });
                });

            modelBuilder.Entity("ProductCRUD.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "เมล็ดกาแฟโรบัสต้าแท้เข้มข้น",
                            Name = "กาแฟปรุงสำเร็จผง 3 in 1",
                            Price = 129.00m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "ข้าวเกี่ยวใหม่ นุ่มเหนียวหอมอร่อย",
                            Name = "ข้าวหอมมะลิแท้ 100% (5 กก.)",
                            Price = 245.00m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "รสชาติจัดจ้านถึงเครื่อง แพ็ก 10 ซอง",
                            Name = "บะหมี่กึ่งสำเร็จรูปรสต้มยำกุ้ง",
                            Price = 65.00m,
                            Stock = 340
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "ปรับแรงลมได้ 3 ระดับ ประหยัดไฟเบอร์ 5",
                            Name = "พัดลมตั้งพื้น 16 นิ้ว",
                            Price = 599.00m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "หม้อในเคลือบสารกันติด หุงข้าวได้หลากหลาย",
                            Name = "หม้อหุงข้าวดิจิทัล 1.8 ลิตร",
                            Price = 1490.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "ต้มน้ำเดือดเร็ว ตัดไฟอัตโนมัติเมื่อเดือด",
                            Name = "กาต้มน้ำไฟฟ้าสแตนเลส (1.5 ลิตร)",
                            Price = 390.00m,
                            Stock = 65
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "ดีไซน์ประคองมือ ลดอาการปวดข้อมือ",
                            Name = "เมาส์ไร้สายบลูทูธ Ergonomic",
                            Price = 450.00m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Blue Switch เสียงคลิกสะใจ มีไฟ RGB",
                            Name = "คีย์บอร์ดกลไก Mechanical",
                            Price = 1890.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "รองรับการชาร์จเร็ว Fast Charge พกพาง่าย",
                            Name = "พาวเวอร์แบงค์ความจุ 20,000 mAh",
                            Price = 690.00m,
                            Stock = 95
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "ผ้าเนื้อนุ่ม ระบายอากาศดี ใส่สบายได้ทุกวัน",
                            Name = "เสื้อยืดผ้าคอตตอนทรง Oversize",
                            Price = 290.00m,
                            Stock = 180
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "ผ้ายีนส์ยืดหยุ่นเล็กน้อย ทรงสวยแมตช์ง่าย",
                            Name = "กางเกงยีนส์ขายาวทรงกระบอก",
                            Price = 590.00m,
                            Stock = 85
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "มีช่องใส่โน้ตบุ๊กขนาด 15.6 นิ้ว ผ้ากันละอองน้ำ",
                            Name = "กระเป๋าเป้สะพายหลังกันน้ำ",
                            Price = 890.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "บางเบา ซึมไว ไม่เหนียวเหนอะหนะและไม่เป็นคราบ",
                            Name = "ครีมกันแดดสูตรน้ำ SPF50+",
                            Price = 420.00m,
                            Stock = 110
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "เติมความชุ่มชื้นให้ผิวหน้า ดูอิ่มน้ำฟูกระชับ",
                            Name = "เซรั่มไฮยาลูรอนเข้มข้น",
                            Price = 580.00m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "เสริมภูมิคุ้มกันให้ร่างกาย บำรุงผิวพรรณ",
                            Name = "วิตามินซีสกัดเข้มข้น (100 เม็ด)",
                            Price = 320.00m,
                            Stock = 90
                        });
                });

            modelBuilder.Entity("ProductCRUD.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2y$12$zNr.4i/.waJKNJuCDTCa3.XTyHAPmoYIHvpFukV2d7E.TQ7gpfl.G",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ProductCRUD.Model.Product", b =>
                {
                    b.HasOne("ProductCRUD.Model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductCRUD.Model.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
